status = [
    "Clippy/rustfmt Test",
    "Test Postgres (12, debian, 11, debian-11-amd64)",
    "Test Postgres (13, debian, 11, debian-11-amd64)",
    "Test Postgres (14, debian, 11, debian-11-amd64)",
    "Test Postgres (14, rockylinux, 9, rockylinux-9-x86_64)",
    "Test Postgres (14, centos, 7, centos-7-x86_64)",
    "Test Postgres (15, debian, 11, debian-11-amd64)",
    "Test Postgres (15, rockylinux, 9, rockylinux-9-x86_64)",
    "Test Postgres (15, centos, 7, centos-7-x86_64)",
    "Test Postgres (16, debian, 11, debian-11-amd64)",
    "Test Postgres (16, rockylinux, 9, rockylinux-9-x86_64)",
    "Test Postgres (16, centos, 7, centos-7-x86_64)",
    "Test Postgres (17, debian, 11, debian-11-amd64)",
    "Test Postgres (17, rockylinux, 9, rockylinux-9-x86_64)",
    "Test Postgres (17, centos, 7, centos-7-x86_64)",
]
delete-merged-branches = true
timeout_sec = 3600 # 60 min
