[package]
name = "hyperloglog"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dependencies.bytecount]
version = "0.6"
features = ["runtime-dispatch-simd"]

[dev-dependencies]
fnv = "1.0.3"
