#!/bin/sh

set -ex

# TODO After we upgrade to 0.4 make this change in docker/ci/Dockerfile and then remove this line.
export PATH=/home/postgres/pgx/0.4/bin:$PATH

print() {
    printf '%s\n' "$*"
}

die() {
    st=${?:-0}
    if [ $st -eq 0 ]; then
        st=2
    fi
    print "$*" >&2
    exit $st
}

usage() {
    die 'build [ -n -pg1[234] ] ( test-crates | test-extension | test-post-install | test-doc | test-updates | clippy)'
}

require_pg_version() {
    [ -n "$pg_version" ] || die 'specify one of -pg12 | -pg13 | -pg14'
}

find_pg_config() {
    if [ -z "$pg_config" ]; then
        require_pg_version
        full_version=$(
            cd "$HOME/.pgx"
            set -- $pg_version.*/pgx-install
            [ "$1" = "$pg_version.*/pgx-install" ] && die "$pg_version not installed in $HOME/.pgx"
            set -- $(dirname $*)
            [ $# -eq 1 ] || die "too many installations for $pg_version, found: $*"
            echo $1)
        pg_config="$HOME/.pgx/$full_version/pgx-install/bin/pg_config"
    fi
    [ -x "$pg_config" ] || die "$pg_config not executable"
}

require_cargo_pgx() {
    [ -n "$cargo_pgx" ] || die 'specify path to cargo-pgx (0.4 series or newer)'
}

require_cargo_pgx_old() {
    [ -n "$cargo_pgx_old" ] || die 'specify path to cargo-pgx (0.2-0.3 series)'
}


[ $# -ge 1 ] || usage

# For reasons we don't yet understand, pgx prevents the cargo cache from
# working across runs UNLESS all pgx commands are run from the 'extension'
# subdirectory of the project.  Any cargo command we need to run from that
# subdirectory, we use CARGO_TARGET_DIR="$extension_CARGO_TARGET_DIR", and for
# all others, CARGO_TARGET_DIR="$top_CARGO_TARGET_DIR".
#
# If each entry in ci.yml `jobs` is guaranteed to be run in isolation, always
# with the target dir freshly copied from the specified cache key, then we
# don't need to bother with CARGO_TARGET_DIR here.
#
# However, this script is derived from one I was using for my local builds
# anyway, and apparently everyone is suffering the slow build times locally,
# so why have more than one way to build?  Why not use the same tool locally
# as the official build uses?
#
# CARGO_TARGET_DIR_NAME allows me to call my target directory '.target'.
# TODO Can we simplify and just force .target here?  It works fine, but I didn't want to surprise people...
if [ -z "$CARGO_TARGET_DIR_NAME" ]; then
    # No default to force us to set it in ci.yml, same place we configure the cache.
    die CARGO_TARGET_DIR_NAME not set
fi
top_CARGO_TARGET_DIR="$PWD/$CARGO_TARGET_DIR_NAME/top"
extension_CARGO_TARGET_DIR="$PWD/$CARGO_TARGET_DIR_NAME/extension"

while [ $# -gt 0 ]; do
    arg="$1"
    shift
    case "$arg" in
        -n)
            nop=:
            ;;

        -pgconfig)
            pg_config="$1"
            shift
            ;;

        -cargo-pgx)
            cargo_pgx="$1"
            shift
            ;;

        -cargo-pgx-old)
            cargo_pgx_old="$1"
            shift
            ;;

        -pgport)
            pg_port="$1"
            shift
            ;;

        -pg1[234])
            pg_version=${arg#-pg}
            pg=pg$pg_version
            [ -z "$pg_port" ] && pg_port=288$pg_version
            ;;

        clippy)
            $nop env "CARGO_TARGET_DIR=$top_CARGO_TARGET_DIR" cargo fetch
            # We need to pick a postgres version to clippy the timescaledb_toolkit crate, but it doesn't matter which one.
            $nop env "CARGO_TARGET_DIR=$top_CARGO_TARGET_DIR" cargo clippy --workspace --features 'pg14 pg_test' -- -D warnings
            ;;

        test-crates)
            # Should find no dependency crates to fetch.  If it finds any, we need to update the cache key.
            $nop env "CARGO_TARGET_DIR=$top_CARGO_TARGET_DIR" cargo fetch
            $nop env "CARGO_TARGET_DIR=$top_CARGO_TARGET_DIR" cargo test --workspace --exclude timescaledb_toolkit
            ;;

        test-extension)
            cd extension
            require_pg_version
            $nop env "CARGO_TARGET_DIR=$extension_CARGO_TARGET_DIR" cargo fetch
            $nop env "CARGO_TARGET_DIR=$extension_CARGO_TARGET_DIR" cargo test --features "$pg pg_test" --no-default-features
            ;;

        install)
            cd extension
            require_pg_version
            find_pg_config
            $nop env "CARGO_TARGET_DIR=$extension_CARGO_TARGET_DIR" cargo pgx install -c "$pg_config"
            ;;

        # Requires extension has been installed.  `install` or `test-extension` takes care of that.
        test-post-install)
            require_pg_version
            find_pg_config
            (
                export CARGO_TARGET_DIR="$top_CARGO_TARGET_DIR"
                $nop cargo pgx stop $pg
                $nop cargo pgx start $pg
                $nop cargo run --manifest-path tools/post-install/Cargo.toml "$pg_config"
                $nop cargo run --manifest-path tools/testrunner/Cargo.toml -- -h localhost -p $pg_port
            )
            ;;

        test-doc)
            require_pg_version
            $nop cargo run -p sql-doctester -- \
                 -h localhost \
                 -p $pg_port \
                 -s "CREATE EXTENSION timescaledb; CREATE EXTENSION timescaledb_toolkit; SET SESSION TIMEZONE TO 'UTC'" \
                 docs
            ;;

        test-updates)
            require_pg_version
            find_pg_config
            require_cargo_pgx
            require_cargo_pgx_old
            (
                export CARGO_TARGET_DIR="$top_CARGO_TARGET_DIR"
                $nop cargo pgx start $pg
                $nop cargo run --manifest-path tools/update-tester/Cargo.toml -- \
                 -h localhost \
                 -p $pg_port \
                 --cache old-versions \
                 . \
                 "$pg_config" \
                 "$cargo_pgx" \
                 "$cargo_pgx_old"
            )
            ;;

        *)
            usage
            ;;
    esac
done
