#!/bin/sh

set -ex

print() {
    printf '%s\n' "$*"
}

die() {
    st=${?:-0}
    if [ $st -eq 0 ]; then
        st=2
    fi
    print "$*" >&2
    exit $st
}

usage() {
    die 'build [ -n -pg1[234] ] ( test-crates | test-extension | install | test-doc | clippy)'
}

require_pg_version() {
    [ -n "$pg_version" ] || die 'specify one of -pg12 | -pg13 | -pg14'
}

find_pg_config() {
    if [ -z "$pg_config" ]; then
        require_pg_version
        pg_config=`sed -ne 's/"//g' -e s/^pg$pg_version=//p ~/.pgx/config.toml`
    fi
    [ -x "$pg_config" ] || die "$pg_config not executable"
}

[ $# -ge 1 ] || usage

while [ $# -gt 0 ]; do
    arg="$1"
    shift
    case "$arg" in
        -n)
            nop=:
            ;;

        -pgconfig)
            pg_config="$1"
            shift
            ;;

        -pgport)
            pg_port="$1"
            shift
            ;;

        -pg1[234])
            pg_version=${arg#-pg}
            pg=pg$pg_version
            [ -z "$pg_port" ] && pg_port=288$pg_version
            ;;

        clippy)
            $nop cargo fetch
            # We need to pick a postgres version to clippy the timescaledb_toolkit crate, but it doesn't matter which one.
            $nop cargo clippy --workspace --features 'pg14 pg_test' -- -D warnings
            ;;

        test-crates)
            # Should find no dependency crates to fetch.  If it finds any, we need to update the cache key.
            $nop cargo fetch
            $nop cargo test --workspace --exclude timescaledb_toolkit
            ;;

        test-extension)
            cd extension
            require_pg_version
            $nop cargo fetch
            $nop cargo test --features "$pg pg_test" --no-default-features
            ;;

        install)
            require_pg_version
            find_pg_config
            (cd extension && $nop cargo pgx install -c "$pg_config")
            $nop cargo run --manifest-path tools/post-install/Cargo.toml "$pg_config"
            ;;

        # Reruns the tests test-extension does if they're left installed.
        # TODO Remove this and testrunner.
        test-post-install)
            require_pg_version
            find_pg_config
            $nop cargo pgx stop $pg
            $nop cargo pgx start $pg
            $nop cargo run --manifest-path tools/testrunner/Cargo.toml -- -h localhost -p $pg_port
            ;;

        test-doc)
            require_pg_version
            $nop cargo pgx start $pg
            $nop cargo run -p sql-doctester -- \
                 -h localhost \
                 -p $pg_port \
                 -s "CREATE EXTENSION timescaledb; CREATE EXTENSION timescaledb_toolkit; SET SESSION TIMEZONE TO 'UTC'" \
                 docs
            $nop cargo pgx stop $pg
            ;;

        *)
            usage
            ;;
    esac
done
