[package]
name = "flat_serialize"
version = "0.1.0"
authors = ["Joshua Lockerman"]
edition = "2021"

[dependencies]
ordered-float = "1.0"
serde = "1.0"

[dev-dependencies]
flat_serialize_macro = {path="../flat_serialize_macro"}
